### ISSUE TITLE
Add example usage code in README

### ISSUE THREAD

**Issue by rly** [rly/ndx-beadl#11]
The README file needs to be updated with example code demonstrating how to use the extension for a common use case.

Secondly, we should copy the example usage code into a unit test to ensure that the code works correctly even when the extension source code changes.

**Comment by mavaylon1** [comment]
@rly can't they refer to the notebook?

**Comment by oruebel** [comment]
I think the example in the README serves a different purpose than the notebook. The example in the readme should be short and sweat, just showing how simple it is to use the extension and what it can do. The notebook then goes into much more detail to do a step-by-step walkthrough.

**Comment by rly** [comment]
I agree with @oruebel . Something like https://github.com/rly/ndx-events and https://github.com/rly/ndx-csd and https://github.com/catalystneuro/ndx-sound

**Comment by mavaylon1** [comment]
#20
