### ISSUE TITLE
Update column order for ``EventsTable`` and ``StatesTable``

### ISSUE THREAD

**Issue by oruebel** [rly/ndx-beadl#12]
This is a very minor, nit-picky, issue. In ``StatesTable`` the ``start_time`` and ``stop_time`` columns are first followed by the ``state_type``. In contrast, in the ``EventsTable`` and ``ActionsTable`` the ``timestamp`` column is listed first. For consistency I would propose to update the schema to list the ``timestamp`` column first also for the ``EventsTable`` and ``ActionsTable``.

**Comment by mavaylon1** [comment]
In the schema, the order matches. I'm not sure why the order changes. I'll look into it.

**Comment by rly** [comment]
Listing the `timestamp` column first for those tables *should* be fine, as far as I know.
