### ISSUE TITLE
Deprection warnings due to use of positional arguments in Container classes

### ISSUE THREAD

**Issue by oruebel** [rly/ndx-beadl#4]
Using the dev branch of HDMF I'm seeing the following deprecation warnings for most Container classes defined here (e.g,. the 
EventsTypesTable and ActionsTTypesTable). 

<img width="1330" alt="Screen Shot 2022-07-15 at 11 39 05 AM" src="https://user-images.githubusercontent.com/10999845/179487163-7953004e-a095-4074-afec-0cdf6a44b03e.png">

I'm not sure if this is an issue in the extension or whether the autogeneration of Container classes in HDMF needs to be updated to use positional arguments.

**Comment by oruebel** [comment]
This may not be an error in the extension code itself. It looks like those classes are autogenerated, so it may be that those arguments are somehow passed a positional arguments to the constructor of the parent class. This warning was added in https://github.com/hdmf-dev/hdmf/pull/730 It may be that the class generator in HDMF need to be updated. @rly any idea.

**Comment by mavaylon1** [comment]
So this is due to the docval in DynamicTable having a warning for args in the init. I'm looking for where args are used.

**Comment by rly** [comment]
@mavaylon1 and I discussed this today. It relates to the use of `call_docval_func`. I raised this issue in HDMF https://github.com/hdmf-dev/hdmf/issues/748
