### ISSUE TITLE
Tasks class fails in example notebook with latest version of HDMF

### ISSUE THREAD

**Issue by oruebel** [rly/ndx-beadl#5]
Could you help me with the following issue.  Using the dev branch of HDMF, I'm getting the following error when trying to run the example notebook. 

<img width="1049" alt="Screen Shot 2022-07-15 at 11 29 57 AM" src="https://user-images.githubusercontent.com/10999845/179488013-eac24e6e-c342-4851-ad03-482812872b82.png">

When looking at the help for the Tasks class, at least at first glance it seems to look ok:

<img width="1322" alt="Screen Shot 2022-07-15 at 11 33 11 AM" src="https://user-images.githubusercontent.com/10999845/179488465-023183c0-05ff-4c3a-a6ad-fea8b53f6762.png">

**Comment by mavaylon1** [comment]
Weird. I am using an older version of dev. I'll take a look.

**Comment by oruebel** [comment]
The following recent PR could be relevant  https://github.com/hdmf-dev/hdmf/pull/741

**Comment by mavaylon1** [comment]
After some fiddling I saw that Tasks has two unnamed datasets, the task_program and the task_schema. I gave them names, but was met with the error that it can't have a name if quantity was "+", then it can't have a name. I commented out quantity so that It's back to 1. This fixed the error; however, we don't have quantity as "+" anymore. Thoughts?

**Comment by oruebel** [comment]
> I commented out quantity so that It's back to 1.

I think that is fine since if you were to use multiple programs I think one would would probably create separate ``Tasks`` rather than having multiple programs for a single task. @rly what do you think?

However, I think we should still investigate the error in HDMF as well, since the schema was valid and the class generation should have still worked.

**Comment by oruebel** [comment]
> I gave them names,

When using a quantity of ``1`` or ``?``, we should use the singular for the names, i.e, we should change the name ``task_programs`` to ``task_program`` and ``task_schemas`` to task_schema``
