### ISSUE TITLE
Define place where EventTypesTable, ActionTypesTable, and StateTypesTable should be stored

### ISSUE THREAD

**Issue by oruebel** [rly/ndx-beadl#6]
Currently the ``EventTypesTable``, ``ActionTypesTable``, and ``StateTypesTable``  are stored in the ``acquisition/`` group in NWB. However, those tables do not contain acquired data but are derived from the task program. On the other hand, they are linked from the ``EventsTable``, ``ActionsTable``, and ``StatesTables`` so it would make sense to keep them together. To address this issue we could, either:

1. Add the ``EventTypesTable``, ``ActionTypesTable``, and ``StateTypesTable`` to the ``Tasks`` type. Since the information is extracted from the task program, I think this would make sense to store those there. The ``quantity`` for the ``Tasks.task_program`` and ``Tasks.task_schema`` should in this case probably change to ``?`` (i.e,. ``zero_or_one``) to allow storage of the tables even if a user does not have the task program
2. We could create a new module ``task_recording`` that contains the:
    * the recorded ``EventsTable``, ``ActionsTable``,  and ``StatesTables`` 
    * the corresponding ``EventTypesTable``, ``ActionTypesTable``, ``StateTypesTable``
    * link to the ``Tasks`` with the taskprogram
3. Do a hybrid of 1. and 2. with:
    * Add ``EventTypesTable``, ``ActionTypesTable``, ``StateTypesTable`` to the ``Tasks``
    * Create a ``task_recording`` module that contains the:
          * recorded ``EventsTable``, ``ActionsTable``,  and ``StatesTables``  
          * Link to the corresponding ``Tasks``

I'm currently leaning towards option 3, but I think any of these options would work.

**Comment by oruebel** [comment]
@rly thoughts?

**Comment by mavaylon1** [comment]
Made the changes mentioned in "1)". However, I'm running into issues with the class generator (Refer to image). To get it working, I did a hack/workaround by setting the types to DynamicTables. But there seems to be an issue with the class generator class considering the previous issue mentioned in #5

**Comment by oruebel** [comment]
> To get it working, I did a hack/workaround by setting the types to DynamicTables

Can you also test with HDMF 3.3.0. If works with 3.3.0 but not latest dev (or 3.3.2) then we know that it is most likely due to  https://github.com/hdmf-dev/hdmf/pull/741 and can ping @rly

**Comment by rly** [comment]
Let me know if the above error is still an issue with the latest HDMF. I like options 1 and 3 and lean toward 3 as well.
