### ISSUE TITLE
``src/pynwb/tests/test_example.py`` not working

### ISSUE THREAD

**Issue by oruebel** [rly/ndx-beadl#8]
``src/pynwb/tests/test_example.py`` needs to be updated to work with the current version of the schema and example files. In particular:

- Task file needs to be updated to use the "LightChasingTask.xml" instead
- ``ActionTable`` and ``ActionTypesTable`` are missing
- ``add_event`` calls need to be updates to use ``event_type`` and ``value`` parameter
-  ``TrailsTable`` needs to be updated to use the ``actions``
- When specifying paths we should use paths relative to the location of the python file to ensure the tests can be run from different folders i.e., use ``with open(os.path.join(test_dir, "BEADL.xsd"), "r")`` instead of ``with open("src/pynwb/tests/BEADL.xsd", "r")``

**Comment by mavaylon1** [comment]
I'm not sure what the point of this file is considering this test is in test_beadl.py. I'm going to delete it.

**Comment by rly** [comment]
This test existed to test the example code that is in the README, which is a little different (less test-y, more demo-y) than the unit tests. I'll open a new issue to add this back in once the example code in the README is updated.
