### ISSUE TITLE
Add unit test for ``plot.py``

### ISSUE THREAD

**Issue by oruebel** [rly/ndx-beadl#9]

**Comment by mavaylon1** [comment]
@oruebel I was looking at plot.py and wasn't sure what you had in mind for a unit test. I had the idea of removing all the code of retrieving the y_values into separate functions and then test those. Let me know what you think/had in mind.

**Comment by oruebel** [comment]
> . I had the idea of removing all the code of retrieving the y_values into separate functions and then test those

Making the functions more modular is a good idea. Testing plots itself is tricky. It's possible to save the plots as a a pixel graphic and then in the unit test compare that the plot generated by the function has not changes. However, that approach is brittle, as different rendering backends or version changes in the plotting libraries can result in slightly different images so that maintaining such tests quickly becomes a pain. For now, I would suggest testing that the functions don't crash and that they return expected values. While that is doesn't cover the behavior of the functions completely, it at least provides basic testing.

**Comment by mavaylon1** [comment]
Yeah I'll make it more modular and test the numerical inputs but I'll leave testing the plot itself for later.
